import {
  TechnologyCategory,
  Product,
  Partner,
  IndustrySolution,
  EngineeringService,
  CaseStudy,
  Organization,
  OrgUser,
  RFQ,
  ResourceRequirement,
  CRMOpportunity,
  PublicEnquiry,
  FeatureFlagsMap,
  AuditLogItem,
} from '../types';

export const initialFeatureFlags: FeatureFlagsMap = {
  public_partner_directory: true, // ON after public content QA
  product_catalog: true, // ON after public content QA
  contact_forms: true, // ON with anti-abuse + monitoring
  enterprise_login: true, // PILOT / ON for previewing enterprise workspace
  partner_login: true, // PILOT / ON for previewing partner workspace
  rfq_submission: true, // PILOT
  rfq_partner_routing: true, // INTERNAL/PILOT
  quotation_upload: true, // PILOT
  engineering_requirements: true, // PILOT
  crm_workspace: true, // INTERNAL
  advanced_search: true, // Faceted search enabled
};

export const initialCategories: TechnologyCategory[] = [
  {
    id: 'cat-asic-soc',
    name: 'ASIC & SoC Architecture',
    slug: 'asic-soc-architecture',
    description: 'Custom digital and mixed-signal silicon implementations from architectural definition to tapeout.',
    iconName: 'Cpu',
    publicationState: 'published',
  },
  {
    id: 'cat-verification',
    name: 'Verification & UVM Testbenches',
    slug: 'verification-uvm-testbenches',
    description: 'SystemVerilog/UVM, formal verification, and hardware emulation for zero-defect silicon.',
    iconName: 'ShieldCheck',
    publicationState: 'published',
  },
  {
    id: 'cat-fpga',
    name: 'FPGA Prototyping & Emulation',
    slug: 'fpga-prototyping-emulation',
    description: 'High-density multi-FPGA prototyping platforms (AMD Xilinx Versal, Intel Agilex) for pre-silicon validation.',
    iconName: 'Layers',
    publicationState: 'published',
  },
  {
    id: 'cat-physical-design',
    name: 'Physical Design & STA',
    slug: 'physical-design-sta',
    description: 'Floorplanning, CTS, place & route, power grid synthesis, and sign-off timing analysis across 3nm–28nm nodes.',
    iconName: 'Boxes',
    publicationState: 'published',
  },
  {
    id: 'cat-embedded-iot',
    name: 'Embedded Systems & Firmware',
    slug: 'embedded-systems-firmware',
    description: 'Bare-metal, RTOS (FreeRTOS, Zephyr), and embedded Linux BSP engineering with secure boot and crypto accelerators.',
    iconName: 'Terminal',
    publicationState: 'published',
  },
  {
    id: 'cat-highspeed-pcb',
    name: 'High-Speed Hardware & SI/PI',
    slug: 'highspeed-hardware-sipi',
    description: 'Multi-gigabit PCB design, 112G PAM4 signal/power integrity simulation, and thermal-mechanical packaging.',
    iconName: 'CircuitBoard',
    publicationState: 'published',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-riscv-800',
    sku: 'SP-RISCV-800',
    name: 'Silphor RV64 Industrial Processor Core',
    slug: 'silphor-rv64-industrial-processor-core',
    categoryId: 'cat-asic-soc',
    categoryName: 'ASIC & SoC Architecture',
    tagline: 'High-performance 64-bit RV64GC quad-core processor with lockstep safety support.',
    description: 'Synthesizable IP core optimized for real-time automotive gateways and high-reliability industrial automation controllers. Features dual-core lockstep execution and hardware ECC.',
    specs: {
      Architecture: 'RISC-V RV64GC (IMA-FDC)',
      'Clock Speed': 'Up to 1.8 GHz on 12nm FinFET',
      'L1 Cache': '32KB I-Cache / 32KB D-Cache with Parity/ECC',
      'Safety Standard': 'ISO 26262 ASIL-B / ASIL-D Ready',
      Bus: 'AXI4 128-bit Coherent Interconnect',
    },
    industryIds: ['ind-automotive', 'ind-industrial'],
    publicationState: 'published',
    vendorId: 'part-silphor-core',
    vendorName: 'Silphor Technologies IP Division',
    featured: true,
    lifecyclePhase: 'Active',
    documents: [
      {
        id: 'doc-riscv-ds',
        title: 'SP-RISCV-800 Architectural Datasheet v2.4',
        docType: 'datasheet',
        fileSize: '4.2 MB',
        version: 'v2.4',
        downloadUrl: '/docs/SP-RISCV-800-datasheet.pdf',
      },
      {
        id: 'doc-riscv-ug',
        title: 'Hardware Integration & Register Map Guide',
        docType: 'user_manual',
        fileSize: '6.8 MB',
        version: 'v2.1',
        downloadUrl: '/docs/SP-RISCV-800-integration.pdf',
      },
    ],
  },
  {
    id: 'prod-serdes-112g',
    sku: 'SP-SERDES-112G',
    name: '112Gbps PAM4 SerDes PHY IP Evaluation Kit',
    slug: '112gbps-pam4-serdes-phy-ip-evaluation-kit',
    categoryId: 'cat-highspeed-pcb',
    categoryName: 'High-Speed Hardware & SI/PI',
    tagline: 'Ultra-low jitter multi-standard SerDes PHY for hyperscale datacenter interconnects.',
    description: 'Silicon-proven 112G long-reach transceiver PHY IP with integrated DSP equalizer, adaptive CTLE, and 3-tap FFE. Designed for 400G/800G Ethernet and PCIe Gen 6.',
    specs: {
      'Data Rate': '19.6 Gbps to 112.5 Gbps PAM4 / NRZ',
      'Reach Capability': '35dB insertion loss at 28 GHz Nyquist',
      'Process Node': '7nm / 5nm / 3nm FinFET',
      Power: '< 4.5 pJ/bit at 112G LR',
      Compliance: 'IEEE 802.3ck, OIF CEI-112G-LR/VSR',
    },
    industryIds: ['ind-telecom', 'ind-datacenter'],
    publicationState: 'published',
    vendorId: 'part-cadence',
    vendorName: 'Cadence Design Systems',
    featured: true,
    lifecyclePhase: 'Sampling',
    documents: [
      {
        id: 'doc-serdes-ds',
        title: 'SP-SERDES-112G Product Brief & Eye Diagrams',
        docType: 'datasheet',
        fileSize: '3.1 MB',
        version: 'v1.6',
        downloadUrl: '/docs/SP-SERDES-112G-brief.pdf',
      },
    ],
  },
  {
    id: 'prod-autosar-ecu',
    sku: 'SP-AUTOSAR-ECU',
    name: 'Automotive Domain Gateway Hardware Controller',
    slug: 'automotive-domain-gateway-hardware-controller',
    categoryId: 'cat-embedded-iot',
    categoryName: 'Embedded Systems & Firmware',
    tagline: 'Production-ready ISO 26262 ASIL-D vehicle gateway with Gigabit TSN Ethernet & CAN-XL.',
    description: 'Ruggedized automotive ECU compute board featuring dual lockstep microcontrollers, hardware security module (HSM EVITA Full), and certified AUTOSAR Classic 4.4 stack.',
    specs: {
      Microcontroller: 'Dual Cortex-R52 + TC397 Tricore',
      Networking: '4x 100/1000BASE-T1 Ethernet, 8x CAN-FD / CAN-XL, 4x LIN',
      Security: 'HSM with AES-256, RSA-4096, Secure Boot',
      OperatingTemp: '-40°C to +125°C AEC-Q100 Grade 1',
      Enclosure: 'IP6K9K Sealed Cast Aluminum',
    },
    industryIds: ['ind-automotive'],
    publicationState: 'published',
    vendorId: 'part-renesas',
    vendorName: 'Renesas Electronics',
    featured: true,
    lifecyclePhase: 'Active',
    documents: [
      {
        id: 'doc-ecu-ds',
        title: 'SP-AUTOSAR-ECU Engineering Specifications',
        docType: 'datasheet',
        fileSize: '5.5 MB',
        version: 'v3.0',
        downloadUrl: '/docs/SP-AUTOSAR-ECU-spec.pdf',
      },
      {
        id: 'doc-ecu-cert',
        title: 'TÜV SÜD ISO 26262 Functional Safety Certificate',
        docType: 'compliance_cert',
        fileSize: '1.2 MB',
        version: '2025',
        downloadUrl: '/docs/ISO-26262-cert.pdf',
      },
    ],
  },
  {
    id: 'prod-fpga-versal',
    sku: 'SP-VERSAL-EMU',
    name: 'Versal Prime Enterprise Emulation System',
    slug: 'versal-prime-enterprise-emulation-system',
    categoryId: 'cat-fpga',
    categoryName: 'FPGA Prototyping & Emulation',
    tagline: 'Modular multi-million ASIC gate emulation system with automated partitioning.',
    description: 'Enterprise rack-mount FPGA board configured with AMD Versal AI Core ACAP for high-capacity pre-silicon software development and RTL hardware acceleration.',
    specs: {
      Capacity: 'Up to 120M Equivalent ASIC Gates',
      Memory: '4x DDR4-3200 64GB ECC SO-DIMM',
      HostInterface: 'PCIe Gen 4 x16 Host Link',
      Debugging: 'Deep trace buffer with real-time waveform capture',
    },
    industryIds: ['ind-telecom', 'ind-aerospace'],
    publicationState: 'published',
    vendorId: 'part-silphor-core',
    vendorName: 'Silphor Prototyping Systems',
    featured: false,
    lifecyclePhase: 'Active',
    documents: [
      {
        id: 'doc-versal-ds',
        title: 'SP-VERSAL-EMU Hardware User Guide',
        docType: 'user_manual',
        fileSize: '7.9 MB',
        version: 'v2.0',
        downloadUrl: '/docs/SP-VERSAL-EMU-guide.pdf',
      },
    ],
  },
  {
    id: 'prod-rad-hardsys',
    sku: 'SP-RAD-SPACE',
    name: 'Radiation-Tolerant Space-Grade Compute Module',
    slug: 'radiation-tolerant-space-grade-compute-module',
    categoryId: 'cat-asic-soc',
    categoryName: 'ASIC & SoC Architecture',
    tagline: 'CubeSat and deep-space telemetry processor resistant to TID > 100 krad(Si).',
    description: 'Space-qualified compute unit featuring triple modular redundancy (TMR) on critical control registers, latch-up immune silicon, and SpaceWire transceiver ports.',
    specs: {
      RadiationTolerance: 'TID > 100 krad(Si), SEL immune to LET > 80 MeV-cm2/mg',
      Interface: '4x SpaceWire, MIL-STD-1553B, redundant SPI',
      Screening: 'ECSS-Q-ST-60C / MIL-PRF-38535 Class V',
      PowerSupply: 'Isolated 28V Satellite Bus input',
    },
    industryIds: ['ind-aerospace'],
    publicationState: 'published',
    vendorId: 'part-silphor-core',
    vendorName: 'Silphor Space Systems',
    featured: true,
    lifecyclePhase: 'Sampling',
    documents: [
      {
        id: 'doc-rad-ds',
        title: 'SP-RAD-SPACE Heavy Ion Radiation Test Report',
        docType: 'application_note',
        fileSize: '8.4 MB',
        version: 'v1.1',
        downloadUrl: '/docs/SP-RAD-SPACE-rad-test.pdf',
      },
    ],
  },
  {
    id: 'prod-edge-npu',
    sku: 'SP-NPU-16TOPS',
    name: 'Ultra-Compact 16 TOPS Edge AI NPU Accelerator',
    slug: 'ultra-compact-16-tops-edge-ai-npu-accelerator',
    categoryId: 'cat-asic-soc',
    categoryName: 'ASIC & SoC Architecture',
    tagline: 'Sub-3W neural network inferencing silicon for industrial vision and robotics.',
    description: 'Hardware neural engine supporting INT8/INT4/FP16 models (YOLOv8, MobileNet, Transformer vision). Direct camera sensor interface via 4-lane MIPI CSI-2.',
    specs: {
      PeakPerformance: '16.4 TOPS (INT8) / 32.8 TOPS (INT4)',
      PowerEfficiency: '> 6 TOPS per Watt',
      FrameworkSupport: 'ONNX, TensorFlow Lite, PyTorch quantization',
      CameraInput: 'Dual MIPI CSI-2 D-PHY v2.1',
    },
    industryIds: ['ind-industrial', 'ind-medical'],
    publicationState: 'published',
    vendorId: 'part-synopsys',
    vendorName: 'Synopsys Design IP',
    featured: false,
    lifecyclePhase: 'Active',
    documents: [
      {
        id: 'doc-npu-ds',
        title: 'SP-NPU-16TOPS Architecture & Compiler Guide',
        docType: 'datasheet',
        fileSize: '4.8 MB',
        version: 'v2.2',
        downloadUrl: '/docs/SP-NPU-16TOPS-datasheet.pdf',
      },
    ],
  },
];

export const initialPartners: Partner[] = [
  {
    id: 'part-globalfoundries',
    name: 'GlobalFoundries',
    type: 'foundry',
    tier: 'Strategic',
    country: 'United States & Germany',
    headquarters: 'Malta, NY / Dresden, Germany',
    website: 'https://globalfoundries.com',
    description: 'Global specialty semiconductor foundry delivering differentiated silicon across 22FDX, 12LP+, and silicon photonics platforms.',
    capabilities: ['22FDX Ultra-Low Power RF', '12LP+ FinFET Logic', 'SiPh Silicon Photonics', 'AEC-Q100 Auto Qualification'],
    certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ITAR Registered'],
    publicationState: 'published',
    profileApprovalStatus: 'approved',
    contactEmail: 'silphor-alliance@gf.com',
  },
  {
    id: 'part-tsmc-alliance',
    name: 'TSMC Design Center Alliance',
    type: 'foundry',
    tier: 'Strategic',
    country: 'Taiwan',
    headquarters: 'Hsinchu, Taiwan',
    website: 'https://tsmc.com',
    description: 'World-leading pure-play foundry offering advanced FinFET and GAA nodes down to N3 and N2 with comprehensive 3DFabric packaging.',
    capabilities: ['N5 / N4 / N3 FinFET', 'CoWoS 2.5D Packaging', 'InFO Wafer-Level Packaging', 'Automotive N5A Node'],
    certifications: ['ISO 9001', 'IATF 16949', 'ISO 27001', 'ANSI/ESD S20.20'],
    publicationState: 'published',
    profileApprovalStatus: 'approved',
    contactEmail: 'dca-partner@tsmc.com',
  },
  {
    id: 'part-cadence',
    name: 'Cadence Design Systems',
    type: 'principal_oem',
    tier: 'Premier',
    country: 'United States',
    headquarters: 'San Jose, CA',
    website: 'https://cadence.com',
    description: 'Pioneering provider of electronic design automation software, hardware emulation (Palladium), and standard silicon IP.',
    capabilities: ['Innovus Implementation', 'Palladium Z2 Emulation', 'SerDes & DDR IP', 'Voltus Power Signoff'],
    certifications: ['ISO 26262 Tool Confidence Level 1 (TCL1)', 'ISO 9001'],
    publicationState: 'published',
    profileApprovalStatus: 'approved',
    contactEmail: 'silphor-partner@cadence.com',
  },
  {
    id: 'part-synopsys',
    name: 'Synopsys Corporation',
    type: 'principal_oem',
    tier: 'Premier',
    country: 'United States',
    headquarters: 'Sunnyvale, CA',
    website: 'https://synopsys.com',
    description: 'World leader in silicon-to-software solutions, providing market-leading EDA tools, DesignWare IP, and application security.',
    capabilities: ['Fusion Compiler', 'ZeBu Server Emulation', 'DesignWare Security IP', 'PrimeTime STA'],
    certifications: ['ISO 26262 ASIL-D Certified Flow', 'ISO 9001'],
    publicationState: 'published',
    profileApprovalStatus: 'approved',
    contactEmail: 'partner-ecosystem@synopsys.com',
  },
  {
    id: 'part-foxconn',
    name: 'Foxconn Industrial Solutions',
    type: 'vendor',
    tier: 'Strategic',
    country: 'Taiwan & Vietnam',
    headquarters: 'New Taipei, Taiwan',
    website: 'https://foxconn.com',
    description: 'Global electronics contract manufacturing services, precision tooling, and high-density surface mount assembly.',
    capabilities: ['Surface Mount Technology (SMT)', 'Die Bonding & Wire Bonding', 'Functional Test Chambers', 'High-Volume Box Build'],
    certifications: ['ISO 13485 (Medical)', 'IATF 16949', 'AS9100D (Aerospace)'],
    publicationState: 'published',
    profileApprovalStatus: 'approved',
    contactEmail: 'enterprise-mfg@foxconn.com',
  },
  {
    id: 'part-sv-vlsi-labs',
    name: 'Silicon Valley VLSI Labs',
    type: 'engineering_provider',
    tier: 'Certified',
    country: 'United States & India',
    headquarters: 'Santa Clara, CA & Bangalore',
    website: 'https://sv-vlsi.example.com',
    description: 'Specialized design house offering dedicated UVM verification pods, 5nm physical design engineers, and embedded firmware specialists.',
    capabilities: ['SystemVerilog/UVM Verification Pods', 'Physical Design 5nm–28nm', 'Analog Layout', 'PCIe Gen 6 Protocol VIP'],
    certifications: ['ISO 9001', 'ITAR Compliant Facility'],
    publicationState: 'published',
    profileApprovalStatus: 'approved',
    contactEmail: 'priya.sharma@sv-vlsi.example.com',
  },
  {
    id: 'part-euromicro',
    name: 'EuroMicro Systems Ltd.',
    type: 'distributor',
    tier: 'Premier',
    country: 'Germany',
    headquarters: 'Munich, Germany',
    website: 'https://euromicro.example.com',
    description: 'Specialized Pan-European distributor for high-reliability semiconductor IP, evaluation boards, and Mil-Aero components.',
    capabilities: ['Pan-European Logistics Hub', 'Buffer Stock Management', 'Component Screening', 'Export Control Compliance'],
    certifications: ['EN 9120', 'ISO 9001'],
    publicationState: 'published',
    profileApprovalStatus: 'approved',
    contactEmail: 'david.chen@euromicro.example.com',
  },
];

export const initialIndustries: IndustrySolution[] = [
  {
    id: 'ind-automotive',
    name: 'Automotive & EV Mobility',
    slug: 'automotive-ev-mobility',
    summary: 'ISO 26262 ASIL-D qualified electronics, AUTOSAR architecture, and battery management ASICs.',
    description: 'From zonal controllers and high-performance ADAS compute to battery management system (BMS) silicon, Silphor delivers certified automotive electronic solutions that meet stringent thermal, functional safety, and AEC-Q100 standards.',
    keyUseCases: [
      'Zonal Gateway Controllers with TSN Ethernet',
      'ADAS Sensor Fusion (LiDAR, Radar & Cameras)',
      '800V SiC Inverter Gate Drivers',
      'Over-The-Air (OTA) Secure Firmware Upgrades',
    ],
    complianceStandards: ['ISO 26262 ASIL-B to D', 'AEC-Q100 Grade 0-1', 'AUTOSAR Classic 4.4 & Adaptive', 'ISO 21434 Cybersecurity'],
    featuredTech: ['SP-AUTOSAR-ECU', 'SP-RISCV-800', 'Automotive UVM VIP'],
    publicationState: 'published',
  },
  {
    id: 'ind-aerospace',
    name: 'Aerospace & Defense',
    slug: 'aerospace-defense',
    summary: 'DO-254 / DO-178C avionics silicon, radiation-tolerant CubeSat payloads, and MIL-STD electronics.',
    description: 'Mission-critical hardware with full traceability, single-event latch-up (SEL) immunity, and ITAR compliance for commercial aviation, satellite constellations, and defense radar arrays.',
    keyUseCases: [
      'Low Earth Orbit (LEO) Telemetry SoCs',
      'Flight Control Computer DO-254 Level A Hardware',
      'Electronic Warfare DSP Accelerator Boards',
      'MIL-STD-1553B / ARINC 429 Avionics Gateways',
    ],
    complianceStandards: ['DO-254 (DAL A)', 'DO-178C (DAL A)', 'MIL-PRF-38535 Class V', 'ITAR / EAR Compliant'],
    featuredTech: ['SP-RAD-SPACE', 'Radiation-Tolerant FPGA', 'Lockstep ARM/RISC-V'],
    publicationState: 'published',
  },
  {
    id: 'ind-telecom',
    name: 'Telecommunications & 5G/6G',
    slug: 'telecommunications-5g-6g',
    summary: 'High-throughput 800G optical transceivers, O-RAN baseband processors, and 112G PAM4 SerDes.',
    description: 'Enabling next-generation hyperscale cloud infrastructure and telecommunications radio networks with silicon-proven high-speed IP and low-power digital signal processing.',
    keyUseCases: [
      '800G Data Center Ethernet Switches',
      'Open-RAN Distributed Unit (O-DU) Acceleration',
      'Massive MIMO Beamforming DSP Silicon',
      'PCIe Gen 6 / CXL 3.0 Optical Interconnects',
    ],
    complianceStandards: ['IEEE 802.3ck / 802.3df', 'O-RAN Alliance v7.0', 'OIF CEI-112G', 'Telcordia GR-63-CORE'],
    featuredTech: ['SP-SERDES-112G', 'SP-OPTIC-800G', 'High-Speed SI/PI Tools'],
    publicationState: 'published',
  },
  {
    id: 'ind-industrial',
    name: 'Industrial Automation & Robotics',
    slug: 'industrial-automation-robotics',
    summary: 'Real-time deterministic motor control, IEC 62443 cyber-hardened IoT gateways, and sub-millisecond EtherCAT.',
    description: 'Robust silicon and turnkey boards engineered to operate reliably in harsh electromagnetic and high-vibration environments across smart factories and collaborative robotics.',
    keyUseCases: [
      'Multi-Axis Servo Motor Control with FOC',
      'Industrial Safety Controllers (SIL-3)',
      'Sub-microsecond Precision Time Protocol (IEEE 1588)',
      'Predictive Maintenance Vibration Sensor Hubs',
    ],
    complianceStandards: ['IEC 61508 SIL-3', 'IEC 62443-4-2', 'IP67 / IP6K9K Enclosures', 'EMC EN 61000-6-2'],
    featuredTech: ['SP-RISCV-800', 'SP-NPU-16TOPS', 'EtherCAT Master Stack'],
    publicationState: 'published',
  },
  {
    id: 'ind-medical',
    name: 'Medical & Diagnostic Electronics',
    slug: 'medical-diagnostic-electronics',
    summary: 'ISO 13485 compliant patient telemetry, ultra-low power biometric ICs, and FDA-ready architectures.',
    description: 'Precision medical electronics designed for long battery life, low-noise analog signal acquisition, and patient safety isolation.',
    keyUseCases: [
      'Continuous Glucose Monitor (CGM) Sub-10μA SoCs',
      'Portable Ultrasound Beamformer Silicon',
      'Implantable Cardiac Telemetry Modules',
      'Digital Pathology Edge AI Analyzers',
    ],
    complianceStandards: ['ISO 13485', 'IEC 60601-1-2 EMC', 'FDA 21 CFR Part 820', 'IEC 62304 Medical Software'],
    featuredTech: ['SP-BLE-IOTX', 'Ultra-Low Noise Analog Front-End'],
    publicationState: 'published',
  },
];

export const initialEngineeringServices: EngineeringService[] = [
  {
    id: 'serv-turnkey-asic',
    title: 'Turnkey ASIC / SoC Development',
    domain: 'ASIC & SoC',
    description: 'End-to-end silicon delivery: system architecture, RTL specification, synthesis, verification, DFT, physical design, and foundry tapeout management.',
    deliverables: [
      'Architectural Spec & Microarchitecture Spec (MAS)',
      'Fully synthesizable Verilog/SystemVerilog RTL',
      'Tapeout GDSII / OASIS sign-off database',
      'First-silicon bring-up plan and test bench',
    ],
    toolsAndStandards: ['Cadence Innovus', 'Synopsys Fusion Compiler', 'Mentor Tessent DFT', 'TSMC / GF PDKs'],
    leadTimeWeeks: '24–36 Weeks',
    publicationState: 'published',
  },
  {
    id: 'serv-uvm-verification',
    title: 'Advanced Functional Verification & UVM',
    domain: 'Verification & UVM',
    description: 'Constrained random verification, custom SystemVerilog/UVM testbench development, assertions (SVA), and formal mathematical proofs for tapeout confidence.',
    deliverables: [
      'UVM Testbench Architecture & Scoreboard',
      'Constrained-random test suites and sequence libraries',
      '100% Functional & Code Coverage Sign-off Report',
      'Formal Verification Invariant Proofs',
    ],
    toolsAndStandards: ['Cadence Xcelium', 'Synopsys VCS', 'Siemens Questa', 'JasperGold Formal'],
    leadTimeWeeks: '8–16 Weeks',
    publicationState: 'published',
  },
  {
    id: 'serv-physical-design',
    title: 'Physical Design & STA Timing Closure',
    domain: 'ASIC & SoC',
    description: 'Deep sub-micron floorplanning, clock tree synthesis (CTS), multi-corner multi-mode (MCMM) timing closure, and physical DRC/LVS/ERC sign-off down to 3nm.',
    deliverables: [
      'Optimized Floorplan & Power Grid Mesh',
      'Low-power CTS with CTS skew < 15ps',
      'Timing Sign-off Reports across 64+ PVT corners',
      'Calibre DRC/LVS clean GDSII',
    ],
    toolsAndStandards: ['Cadence Innovus / Tempus', 'Synopsys PrimeTime / StarRC', 'Siemens Calibre'],
    leadTimeWeeks: '12–20 Weeks',
    publicationState: 'published',
  },
  {
    id: 'serv-fpga-proto',
    title: 'FPGA Prototyping & Emulation Services',
    domain: 'FPGA',
    description: 'Mapping multi-million gate ASIC designs onto high-end AMD Xilinx Versal and Intel Agilex FPGAs for early pre-silicon driver and firmware validation.',
    deliverables: [
      'Automated multi-FPGA partitioning script',
      'Transceiver clocking and memory controller wrapper',
      'Virtual I/O and PCIe host driver testbench',
      'Turnkey hardware rack unit with remote access',
    ],
    toolsAndStandards: ['Vivado Design Suite', 'Quartus Prime Pro', 'HAPS Hardware', 'Palladium'],
    leadTimeWeeks: '6–12 Weeks',
    publicationState: 'published',
  },
  {
    id: 'serv-embedded-bsp',
    title: 'Embedded Firmware & RTOS / Linux BSP',
    domain: 'Embedded & Firmware',
    description: 'Hardware bring-up, U-Boot bootloader customization, secure boot chain integration, kernel driver authoring, and AUTOSAR MCAL software stack development.',
    deliverables: [
      'Custom Board Support Package (BSP)',
      'Cryptographically signed Secure Boot Loader',
      'Device Drivers for PCIe, SPI, I2C, TSN Ethernet',
      'Yocto / Buildroot Linux Distribution',
    ],
    toolsAndStandards: ['Yocto Project', 'FreeRTOS / Zephyr', 'Lauterbach TRACE32', 'Vector CANoe'],
    leadTimeWeeks: '6–14 Weeks',
    publicationState: 'published',
  },
  {
    id: 'serv-highspeed-hardware',
    title: 'High-Speed Hardware & SI/PI Simulation',
    domain: 'PCB & Hardware',
    description: 'Design of complex 16-to-32 layer boards, 3D electromagnetic modeling of high-speed SerDes vias and traces, and power delivery network (PDN) impedance optimization.',
    deliverables: [
      'Schematic and 24+ Layer PCB Layout Database',
      '3D EM Simulation Reports (Insertion Loss, Return Loss, Crosstalk)',
      'PDN Target Impedance Simulation up to 100MHz',
      'Gerber / ODB++ Manufacturing Package',
    ],
    toolsAndStandards: ['Altium Designer', 'Cadence Allegro', 'Ansys HFSS / SIwave', 'Keysight ADS'],
    leadTimeWeeks: '8–14 Weeks',
    publicationState: 'published',
  },
];

export const initialCaseStudies: CaseStudy[] = [
  {
    id: 'cs-adas-radar',
    title: 'First-Pass Silicon Success on 16nm Automotive Radar SoC',
    clientIndustry: 'Tier-1 Automotive OEM (Munich, Germany)',
    challenge: 'Customer faced aggressive 14-month schedule to build an integrated 77GHz radar processing SoC requiring ISO 26262 ASIL-D certification with zero post-silicon silicon re-spins.',
    solution: 'Silphor deployed a dedicated 12-engineer pod providing RTL microarchitecture, dual-core lockstep verification with UVM, and complete MCMM physical design flow in 16nm FinFET.',
    quantifiedImpact: 'Delivered tapeout 3 weeks ahead of schedule. Achieved 100% functional test coverage with 0 silicon respins and full TÜV SÜD safety signoff.',
    durationMonths: 14,
    featured: true,
    publicationState: 'published',
  },
  {
    id: 'cs-leo-satellite',
    title: 'Radiation-Hardened Telemetry Processor for 120-Satellite Constellation',
    clientIndustry: 'Commercial Aerospace Operator (Toulouse, France)',
    challenge: 'Commercial off-the-shelf microcontrollers suffered destructive single-event latchups during radiation chamber tests. Needed a drop-in radiation-tolerant replacement within 9 months.',
    solution: 'Engineered custom RISC-V SoC incorporating Triple Modular Redundancy (TMR) voting logic on all registers and fault-tolerant ECC caches mapped to radiation-tested silicon.',
    quantifiedImpact: 'Surpassed 120 krad(Si) TID without latchup. Reduced in-orbit power consumption by 42% compared to legacy rad-hard processors.',
    durationMonths: 9,
    featured: true,
    publicationState: 'published',
  },
  {
    id: 'cs-800g-datacenter',
    title: '112Gbps PAM4 SerDes PHY Verification for AI Hyperscale Switches',
    clientIndustry: 'Cloud Infrastructure Semiconductor Unicorn (San Jose, CA)',
    challenge: 'High-density switch chip containing 64 parallel 112G channels required exhaustive mixed-signal and protocol verification before costly 5nm wafer fabrication.',
    solution: 'Constructed automated UVM multi-channel test environment with randomized jitter injection, adaptive equalizer tracking, and hardware emulator acceleration.',
    quantifiedImpact: 'Identified 18 critical corner-case protocol bugs pre-silicon. Successfully achieved 800G line rate on first wafer lot with BER < 10^-12.',
    durationMonths: 11,
    featured: true,
    publicationState: 'published',
  },
];

export const initialOrganizations: Organization[] = [
  {
    id: 'org-apex-robotics',
    name: 'Apex Robotics Systems',
    type: 'Customer',
    country: 'United States',
    domain: 'apexrobotics.io',
    kybStatus: 'verified',
    ndaSigned: true,
  },
  {
    id: 'org-silicon-micro',
    name: 'NextGen Silicon Micro',
    type: 'Principal',
    country: 'Taiwan',
    domain: 'nextgensilicon.tw',
    kybStatus: 'verified',
    ndaSigned: true,
  },
  {
    id: 'org-euromicro',
    name: 'EuroMicro Systems Ltd.',
    type: 'Distributor',
    country: 'Germany',
    domain: 'euromicro.example.com',
    kybStatus: 'verified',
    ndaSigned: true,
  },
  {
    id: 'org-foxconn',
    name: 'Foxconn Industrial Solutions',
    type: 'Vendor',
    country: 'Taiwan',
    domain: 'foxconn.com',
    kybStatus: 'verified',
    ndaSigned: true,
  },
  {
    id: 'org-sv-vlsi',
    name: 'Silicon Valley VLSI Labs',
    type: 'EngineeringPartner',
    country: 'United States',
    domain: 'sv-vlsi.example.com',
    kybStatus: 'verified',
    ndaSigned: true,
  },
  {
    id: 'org-silphor-internal',
    name: 'Silphor Technologies HQ',
    type: 'SilphorInternal',
    country: 'Global',
    domain: 'silphor.com',
    kybStatus: 'verified',
    ndaSigned: true,
  },
];

export const initialUsers: OrgUser[] = [
  {
    id: 'usr-customer-1',
    orgId: 'org-apex-robotics',
    orgName: 'Apex Robotics Systems',
    name: 'Dr. Marcus Vance',
    email: 'marcus.vance@apexrobotics.io',
    role: 'customer',
    title: 'Chief Hardware Architect',
    token: 'token-customer-vance',
  },
  {
    id: 'usr-principal-1',
    orgId: 'org-silicon-micro',
    orgName: 'NextGen Silicon Micro',
    name: 'Elena Rostova',
    email: 'elena.rostova@nextgensilicon.tw',
    role: 'principal_oem',
    title: 'VP Silicon Products & IP',
    token: 'token-principal-rostova',
  },
  {
    id: 'usr-distributor-1',
    orgId: 'org-euromicro',
    orgName: 'EuroMicro Systems Ltd.',
    name: 'David Chen',
    email: 'david.chen@euromicro.example.com',
    role: 'distributor',
    title: 'Director of Commercial Channels',
    token: 'token-distributor-chen',
  },
  {
    id: 'usr-vendor-1',
    orgId: 'org-foxconn',
    orgName: 'Foxconn Industrial Solutions',
    name: 'Kenji Takahashi',
    email: 'kenji.takahashi@foxconn.com',
    role: 'vendor',
    title: 'VP Manufacturing Operations',
    token: 'token-vendor-takahashi',
  },
  {
    id: 'usr-provider-1',
    orgId: 'org-sv-vlsi',
    orgName: 'Silicon Valley VLSI Labs',
    name: 'Priya Sharma',
    email: 'priya.sharma@sv-vlsi.example.com',
    role: 'engineering_provider',
    title: 'Senior Engineering Director',
    token: 'token-provider-sharma',
  },
  {
    id: 'usr-silphor-admin',
    orgId: 'org-silphor-internal',
    orgName: 'Silphor Technologies HQ',
    name: 'Anand Kumar',
    email: 'anand.kumar@silphor.com',
    role: 'silphor_business_user',
    title: 'VP Global Technical Solutions & Ops',
    token: 'token-admin-silphor',
  },
];

export const initialRFQs: RFQ[] = [
  {
    id: 'RFQ-2026-1042',
    title: 'Automotive Zonal Compute Board & 16nm SoC Tapeout',
    customerId: 'usr-customer-1',
    customerName: 'Dr. Marcus Vance',
    customerOrgId: 'org-apex-robotics',
    customerOrgName: 'Apex Robotics Systems',
    requirementDescription: 'Turnkey development of custom ISO 26262 ASIL-D compute board featuring RISC-V quad-core processor with 4x TSN Ethernet and 8x CAN-XL controllers. Includes pre-silicon emulation, UVM verification, and pilot batch of 250 engineering samples.',
    tags: ['Automotive', 'ASIL-D', '16nm FinFET', 'RISC-V', 'TSN Ethernet'],
    targetDate: '2026-12-15',
    estimatedVolumePerYear: 75000,
    lifecycleStatus: 'bidding',
    qualification: {
      category: 'Turnkey Silicon & Embedded Hardware',
      geography: 'North America & Germany',
      urgency: 'high',
      completenessScore: 94,
      assignedOwner: 'Anand Kumar (Silphor Ops)',
      followUpDate: '2026-10-14',
      qualificationNotes: 'High-value customer with secured series C funding. Architecture spec reviewed and technically complete.',
    },
    assignedPartners: [
      {
        partnerId: 'part-globalfoundries',
        partnerName: 'GlobalFoundries',
        assignedAt: '2026-10-01T10:00:00Z',
        dueDate: '2026-10-20T18:00:00Z',
        status: 'viewed',
        confidentialityAccepted: true,
      },
      {
        partnerId: 'part-sv-vlsi-labs',
        partnerName: 'Silicon Valley VLSI Labs',
        assignedAt: '2026-10-01T10:00:00Z',
        dueDate: '2026-10-20T18:00:00Z',
        status: 'submitted',
        confidentialityAccepted: true,
      },
      {
        partnerId: 'part-foxconn',
        partnerName: 'Foxconn Industrial Solutions',
        assignedAt: '2026-10-02T14:30:00Z',
        dueDate: '2026-10-22T18:00:00Z',
        status: 'submitted',
        confidentialityAccepted: true,
      },
    ],
    quotations: [
      {
        id: 'quote-sv-1042',
        rfqId: 'RFQ-2026-1042',
        partnerId: 'part-sv-vlsi-labs',
        partnerName: 'Silicon Valley VLSI Labs',
        currentVersion: 2,
        status: 'submitted',
        updatedAt: '2026-10-04T16:20:00Z',
        versions: [
          {
            version: 1,
            nreCostUsd: 480000,
            unitPriceUsd: 142.5,
            currency: 'USD',
            moq: 1000,
            leadTimeWeeks: 22,
            technicalProposalNotes: 'Proposal covering full UVM testbench and 16nm physical design. First tapeout milestone at month 5.',
            commercialNotes: 'Payment schedule: 30% upfront, 40% at RTL freeze, 30% at GDSII signoff.',
            attachmentName: 'SV_VLSI_Tech_Proposal_v1.pdf',
            submittedAt: '2026-10-03T09:15:00Z',
            submittedBy: 'Priya Sharma',
          },
          {
            version: 2,
            nreCostUsd: 440000,
            unitPriceUsd: 135.0,
            currency: 'USD',
            moq: 1000,
            leadTimeWeeks: 20,
            technicalProposalNotes: 'Optimized proposal utilizing pre-verified Silphor RISC-V VIP to accelerate schedule by 2 weeks.',
            commercialNotes: 'Volume discount tier: $122.00 at 50,000+ annual run rate.',
            attachmentName: 'SV_VLSI_Tech_Proposal_v2_Accelerated.pdf',
            submittedAt: '2026-10-04T16:20:00Z',
            submittedBy: 'Priya Sharma',
          },
        ],
      },
      {
        id: 'quote-fox-1042',
        rfqId: 'RFQ-2026-1042',
        partnerId: 'part-foxconn',
        partnerName: 'Foxconn Industrial Solutions',
        currentVersion: 1,
        status: 'submitted',
        updatedAt: '2026-10-04T11:45:00Z',
        versions: [
          {
            version: 1,
            nreCostUsd: 185000,
            unitPriceUsd: 68.2,
            currency: 'USD',
            moq: 5000,
            leadTimeWeeks: 14,
            technicalProposalNotes: 'Turnkey PCB surface mount manufacturing, automated optical inspection, and thermal test chamber burning.',
            commercialNotes: 'FOB Taiwan / Vietnam. Tooling and stencil fees included in NRE.',
            attachmentName: 'Foxconn_ECU_BoxBuild_Quotation.pdf',
            submittedAt: '2026-10-04T11:45:00Z',
            submittedBy: 'Kenji Takahashi',
          },
        ],
      },
    ],
    attachments: [
      {
        id: 'att-1',
        filename: 'Apex_Zonal_Architecture_Specification_v1.4.pdf',
        fileSize: '6.4 MB',
        uploadedAt: '2026-09-28T14:10:00Z',
      },
      {
        id: 'att-2',
        filename: 'Interface_Connector_Pinout_Matrix.xlsx',
        fileSize: '1.2 MB',
        uploadedAt: '2026-09-28T14:12:00Z',
      },
    ],
    auditTrail: [
      {
        id: 'aud-1',
        timestamp: '2026-09-28T14:15:00Z',
        action: 'RFQ_CREATED',
        actorEmail: 'marcus.vance@apexrobotics.io',
        actorRole: 'customer',
        details: 'RFQ created with 2 technical attachments.',
      },
      {
        id: 'aud-2',
        timestamp: '2026-09-29T09:30:00Z',
        action: 'QUALIFICATION_COMPLETED',
        actorEmail: 'anand.kumar@silphor.com',
        actorRole: 'silphor_business_user',
        details: 'Assigned completeness score 94%. Urgency set to High.',
      },
      {
        id: 'aud-3',
        timestamp: '2026-10-01T10:00:00Z',
        action: 'PARTNERS_ROUTED',
        actorEmail: 'anand.kumar@silphor.com',
        actorRole: 'silphor_business_user',
        details: 'Dispatched controlled access to GlobalFoundries and SV VLSI Labs.',
      },
      {
        id: 'aud-4',
        timestamp: '2026-10-04T16:20:00Z',
        action: 'QUOTATION_VERSION_UPDATED',
        actorEmail: 'priya.sharma@sv-vlsi.example.com',
        actorRole: 'engineering_provider',
        details: 'SV VLSI Labs updated proposal to v2 ($440k NRE, $135 unit).',
      },
    ],
    createdAt: '2026-09-28T14:15:00Z',
    updatedAt: '2026-10-04T16:20:00Z',
  },
  {
    id: 'RFQ-2026-1038',
    title: 'High-Density 112G PAM4 Test Board for Hyperscale Switch',
    customerId: 'usr-customer-1',
    customerName: 'Dr. Marcus Vance',
    customerOrgId: 'org-apex-robotics',
    customerOrgName: 'Apex Robotics Systems',
    requirementDescription: '28-layer Rogers/Megtron-7 high-frequency PCB fabrication with sub-10 mil blind and buried microvias. Must support 64 differential pairs with insertion loss < 0.8dB/inch at 28 GHz.',
    tags: ['High-Speed PCB', '112G PAM4', 'Megtron 7', 'SI/PI Simulation'],
    targetDate: '2026-11-20',
    estimatedVolumePerYear: 500,
    lifecycleStatus: 'comparison',
    qualification: {
      category: 'High-Speed Hardware & SI/PI',
      geography: 'Global',
      urgency: 'critical',
      completenessScore: 98,
      assignedOwner: 'Anand Kumar (Silphor Ops)',
      followUpDate: '2026-10-10',
      qualificationNotes: 'Direct client project with executive sponsorship.',
    },
    assignedPartners: [
      {
        partnerId: 'part-foxconn',
        partnerName: 'Foxconn Industrial Solutions',
        assignedAt: '2026-09-20T08:00:00Z',
        dueDate: '2026-10-05T18:00:00Z',
        status: 'submitted',
        confidentialityAccepted: true,
      },
    ],
    quotations: [
      {
        id: 'quote-fox-1038',
        rfqId: 'RFQ-2026-1038',
        partnerId: 'part-foxconn',
        partnerName: 'Foxconn Industrial Solutions',
        currentVersion: 1,
        status: 'under_review',
        updatedAt: '2026-09-25T14:00:00Z',
        versions: [
          {
            version: 1,
            nreCostUsd: 65000,
            unitPriceUsd: 840.0,
            currency: 'USD',
            moq: 100,
            leadTimeWeeks: 8,
            technicalProposalNotes: 'Megtron 7 laminate with ultra-low profile copper foil. 100% TDR impedance coupon testing included.',
            commercialNotes: 'Lead time 8 weeks from Gerber signoff.',
            submittedAt: '2026-09-25T14:00:00Z',
            submittedBy: 'Kenji Takahashi',
          },
        ],
      },
    ],
    attachments: [
      {
        id: 'att-3',
        filename: '112G_Board_Stackup_Constraints.pdf',
        fileSize: '3.4 MB',
        uploadedAt: '2026-09-18T10:00:00Z',
      },
    ],
    auditTrail: [
      {
        id: 'aud-5',
        timestamp: '2026-09-18T10:05:00Z',
        action: 'RFQ_CREATED',
        actorEmail: 'marcus.vance@apexrobotics.io',
        actorRole: 'customer',
        details: 'RFQ submitted for 112G PAM4 test substrate.',
      },
    ],
    createdAt: '2026-09-18T10:05:00Z',
    updatedAt: '2026-09-25T14:00:00Z',
  },
];

export const initialResourceRequirements: ResourceRequirement[] = [
  {
    id: 'RES-2026-088',
    title: 'Lead SystemVerilog / UVM Verification Specialist',
    customerId: 'usr-customer-1',
    customerOrgName: 'Apex Robotics Systems',
    skill: 'SystemVerilog & UVM Testbench Architecture',
    subSkills: ['SVA Assertions', 'Coverage Closure', 'PCIe Gen 5 VIP', 'Xcelium / VCS'],
    quantity: 3,
    experienceLevel: 'Principal/Staff (9-14y)',
    location: 'Munich, Germany or Remote (CET / IST)',
    workModel: 'Hybrid',
    startDate: '2026-11-01',
    durationMonths: 12,
    shiftAndSite: 'Day shift, Munich R&D Campus or Secured VPN',
    complianceStandards: ['ISO 26262 ASIL-D', 'Clean IP Background Check'],
    budgetHourlyRateMaxUsd: 145,
    mobilizationStatus: 'interviewing',
    assignedProviders: [
      {
        providerId: 'part-sv-vlsi-labs',
        providerName: 'Silicon Valley VLSI Labs',
        routedAt: '2026-10-01T09:00:00Z',
      },
    ],
    candidates: [
      {
        id: 'cand-1',
        providerId: 'part-sv-vlsi-labs',
        providerName: 'Silicon Valley VLSI Labs',
        candidateName: 'Vikramaditya Rao',
        experienceYears: 11,
        keySkills: ['UVM 1.2', 'PCIe 5.0 VIP', 'Formal SVA', 'Synopsys VCS'],
        noticePeriodDays: 14,
        proposedHourlyRateUsd: 135,
        status: 'interview_scheduled',
        submissionNotes: 'Ex-Broadcom verification lead with 3 successful tapeouts in 7nm and 5nm automotive SoCs.',
      },
      {
        id: 'cand-2',
        providerId: 'part-sv-vlsi-labs',
        providerName: 'Silicon Valley VLSI Labs',
        candidateName: 'Ananya Deshmukh',
        experienceYears: 9,
        keySkills: ['UVM', 'SystemC', 'CXL Protocol VIP', 'Cadence Xcelium'],
        noticePeriodDays: 20,
        proposedHourlyRateUsd: 125,
        status: 'submitted',
        submissionNotes: 'Specialized in multi-die coherent fabric verification.',
      },
    ],
    createdAt: '2026-09-29T11:00:00Z',
  },
  {
    id: 'RES-2026-089',
    title: 'Senior 5nm FinFET Physical Design Engineer',
    customerId: 'usr-customer-1',
    customerOrgName: 'Apex Robotics Systems',
    skill: 'Physical Design & Timing Sign-off (5nm/3nm)',
    subSkills: ['Innovus Floorplanning', 'CTS Optimization', 'PrimeTime STA', 'Calibre DRC/LVS'],
    quantity: 2,
    experienceLevel: 'Mid-Senior (5-8y)',
    location: 'Santa Clara, CA or Bangalore',
    workModel: 'Onsite',
    startDate: '2026-11-15',
    durationMonths: 9,
    shiftAndSite: 'Standard Shift, Cleanroom / Secure Lab',
    complianceStandards: ['ITAR Compliance', 'NDA Level 3'],
    budgetHourlyRateMaxUsd: 160,
    mobilizationStatus: 'submitted_profiles',
    assignedProviders: [
      {
        providerId: 'part-sv-vlsi-labs',
        providerName: 'Silicon Valley VLSI Labs',
        routedAt: '2026-10-02T11:00:00Z',
      },
    ],
    candidates: [
      {
        id: 'cand-3',
        providerId: 'part-sv-vlsi-labs',
        providerName: 'Silicon Valley VLSI Labs',
        candidateName: 'Rahul Sen',
        experienceYears: 7,
        keySkills: ['Cadence Innovus', '5nm FinFET', 'Low Power UPF', 'CTS Skew Tuning'],
        noticePeriodDays: 15,
        proposedHourlyRateUsd: 148,
        status: 'submitted',
        submissionNotes: 'Extensive tapeout experience with TSMC N5 and N4 nodes.',
      },
    ],
    createdAt: '2026-10-02T09:30:00Z',
  },
];

export const initialOpportunities: CRMOpportunity[] = [
  {
    id: 'OPP-2026-401',
    title: 'Apex Robotics - Next-Gen Autonomous Compute Contract',
    clientName: 'Dr. Marcus Vance',
    clientOrgName: 'Apex Robotics Systems',
    stage: 'proposal_rfq',
    estimatedValueUsd: 850000,
    leadSource: 'RFQ Submission',
    owner: 'Anand Kumar (Silphor Sales VP)',
    linkedRfqId: 'RFQ-2026-1042',
    nextAction: 'Technical evaluation of SV VLSI proposal v2 with Marcus Vance',
    followUpDate: '2026-10-09',
    activities: [
      {
        id: 'act-1',
        type: 'technical_review',
        note: 'Completed architecture review with Apex team. Clarified CAN-XL throughput metrics.',
        loggedBy: 'Anand Kumar',
        timestamp: '2026-09-30T15:00:00Z',
      },
      {
        id: 'act-2',
        type: 'email',
        note: 'Sent updated NRE schedule breakdown and Foundry wafer slot reservations.',
        loggedBy: 'Anand Kumar',
        timestamp: '2026-10-04T17:00:00Z',
      },
    ],
    createdAt: '2026-09-28T14:20:00Z',
    updatedAt: '2026-10-04T17:00:00Z',
  },
  {
    id: 'OPP-2026-398',
    title: 'EuroMicro - Pan-European Distribution License for SP-RISCV-800',
    clientName: 'David Chen',
    clientOrgName: 'EuroMicro Systems Ltd.',
    stage: 'negotiation',
    estimatedValueUsd: 420000,
    leadSource: 'Partner Referral',
    owner: 'Anand Kumar (Silphor Sales VP)',
    nextAction: 'Finalize territory exclusivity clauses for Germany/Benelux',
    followUpDate: '2026-10-12',
    activities: [
      {
        id: 'act-3',
        type: 'call',
        note: 'Discussed volume commitment: minimum 100,000 unit royalty guarantee per year.',
        loggedBy: 'Anand Kumar',
        timestamp: '2026-10-02T11:30:00Z',
      },
    ],
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-10-02T11:30:00Z',
  },
  {
    id: 'OPP-2026-405',
    title: 'Aerospace Operator - Radiation-Hardened CubeSat Payload Contract',
    clientName: 'Jean-Luc Moreau',
    clientOrgName: 'Orbital Aero Systems',
    stage: 'qualified',
    estimatedValueUsd: 310000,
    leadSource: 'Web Enquiry',
    owner: 'Anand Kumar (Silphor Sales VP)',
    nextAction: 'Schedule qualification call on ECSS-Q-ST-60C test protocols',
    followUpDate: '2026-10-15',
    activities: [
      {
        id: 'act-4',
        type: 'email',
        note: 'Provided heavy ion beam test reports for SP-RAD-SPACE module.',
        loggedBy: 'Anand Kumar',
        timestamp: '2026-10-03T14:15:00Z',
      },
    ],
    createdAt: '2026-10-01T10:00:00Z',
    updatedAt: '2026-10-03T14:15:00Z',
  },
];

export const initialEnquiries: PublicEnquiry[] = [
  {
    id: 'ENQ-2026-071',
    fullName: 'Jean-Luc Moreau',
    companyName: 'Orbital Aero Systems',
    businessEmail: 'jl.moreau@orbital-aero.example.com',
    phone: '+33 5 61 00 22 44',
    enquiryType: 'Hardware Solutions',
    requirementDetails: 'Need radiation-tolerant compute boards for 16-node LEO CubeSat constellation launching Q3 2027. Need details on TID testing and SpaceWire interfaces.',
    country: 'France',
    honeypotCheckPassed: true,
    ipAddressMasked: '194.254.***.***',
    submittedAt: '2026-10-01T09:45:00Z',
    status: 'converted_to_rfq',
  },
  {
    id: 'ENQ-2026-072',
    fullName: 'Sara Lindstrom',
    companyName: 'Nordic Medical Instruments',
    businessEmail: 'sara.l@nordicmed.example.se',
    phone: '+46 8 555 1234',
    enquiryType: 'Engineering Services',
    requirementDetails: 'Looking for a dedicated verification pod to perform UVM verification for a mixed-signal cardiac telemetry ASIC.',
    country: 'Sweden',
    honeypotCheckPassed: true,
    ipAddressMasked: '83.250.***.***',
    submittedAt: '2026-10-04T13:20:00Z',
    status: 'reviewed',
  },
];
